export const experienceData = [
  {
    date: "Dec 2022 - now",
    role: "Dental operator",
    clinic: "red crescent hospital",
    class: "",
  },
  {
    date: "Nov 2022 - oct 2023 ",
    role: "Dental operator",
    clinic: "Senany dental clinics ",
    class: "Class A dental clinics",
  },
  {
    date: "Apr 2022 - Jul 2022",
    role: "Observer and Assistant",
    clinic: "Dr Ahmed Abdel Radi, Qena",
    class: "Class A clinic",
  },
  {
    date: "Feb 2022 - Nov 2022",
    role: "Dental operator",
    clinic: "Dr Doaa Mohamed, Qus-Qena",
    class: "Class B clinic",
  },
  {
    date: "Feb 2022 - Nov 2022",
    role: "Dental operator",
    clinic: "Dr Masoud Clinic, Qena",
    class: "Class B Clinic",
  },
  {
    date: "Jul 2020 - Oct 2020",
    role: "Observer and Assistant",
    clinic: "Dr Elfeel Clinic",
    class: "Class A clinic",
  },
];

export const coursesData = [
  {
    date: "Sep 2022 - Aug 2025",
    course: "ORE course",
  },
  {
    date: "Jun 2022 - Jun 2022",
    course: "Basic and advanced removable prosthodontics",
  },
  {
    date: "Apr 2022 - Apr 2022",
    course: "Basic pediatric dentistry program",
  },
  {
    date: "Feb 2022 - Feb 2022",
    course: "Anterior and posterior composite restorations",
  },
  {
    date: "Nov 2021 - Nov 2021",
    course: "mastering fixed prosthodontics and DSD program",
  },
  {
    date: "Oct 2021 - Oct 2021",
    course: "Basic and advanced minor surgery (25 credit hours)",
  },
];

export const endoImages = [
  {
    src: "/endo/1.png",
    alt: "endo1",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/2.png",
    alt: "endo2",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/3.png",
    alt: "endo3",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/4.png",
    alt: "endo4",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/5.png",
    alt: "endo5",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/6.png",
    alt: "endo6",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/7.png",
    alt: "endo7",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/8.png",
    alt: "endo8",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/9.png",
    alt: "endo9",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/10.png",
    alt: "endo10",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/11.png",
    alt: "endo11",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/12.png",
    alt: "endo12",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/13.png",
    alt: "endo13",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/14.png",
    alt: "endo14",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/15.png",
    alt: "endo15",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/16.png",
    alt: "endo16",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/17.png",
    alt: "endo17",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/18.png",
    alt: "endo18",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
  {
    src: "/endo/19.png",
    alt: "endo19",
    caption: "",
    tags: [{ title: "Endo", value: "endo" }],
    width: 500,
    height: 500,
  },
];

export const estheticImages = [
  {
    src: "/esthetics/1.png",
    alt: "esthetic1",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
  {
    src: "/esthetics/2.jpg",
    alt: "esthetic2",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
  {
    src: "/esthetics/3.png",
    alt: "esthetic3",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
  {
    src: "/esthetics/5.png",
    alt: "esthetic4",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
  {
    src: "/esthetics/6.png",
    alt: "esthetic5",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
  {
    src: "/esthetics/7.png",
    alt: "esthetic7",
    caption: "",
    tags: [{ title: "Esthetics", value: "esthetic" }],
    width: 500,
    height: 500,
  },
];

export const fixedImages = [
  {
    src: "/fixed/1.png",
    alt: "fixed1",
    caption: "",
    tags: [{ title: "Fixed", value: "fixed" }],
    width: 500,
    height: 500,
  },
  {
    src: "/fixed/2.png",
    alt: "fixed2",
    caption: "",
    tags: [{ title: "Fixed", value: "fixed" }],
    width: 500,
    height: 500,
  },
  {
    src: "/fixed/3.png",
    alt: "fixed3",
    caption: "",
    tags: [{ title: "Fixed", value: "fixed" }],
    width: 500,
    height: 500,
  },
  {
    src: "/fixed/4.png",
    alt: "fixed4",
    caption: "",
    tags: [{ title: "Fixed", value: "fixed" }],
    width: 500,
    height: 500,
  },
  {
    src: "/fixed/5.png",
    alt: "fixed5",
    caption: "",
    tags: [{ title: "Fixed", value: "fixed" }],
    width: 500,
    height: 500,
  },
];

export const surgeryImages = [
  {
    src: "/surgery/1.png",
    alt: "surgery1",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/2.png",
    alt: "surgery2",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/3.png",
    alt: "surgery3",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/4.png",
    alt: "surgery4",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/5.png",
    alt: "surgery5",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/6.png",
    alt: "surgery6",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/7.png",
    alt: "surgery7",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/8.png",
    alt: "surgery8",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/9.png",
    alt: "surgery9",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
  {
    src: "/surgery/10.png",
    alt: "surgery10",
    caption: "",
    tags: [{ title: "Surgery", value: "surgery" }],
    width: 500,
    height: 500,
  },
];
