export const experienceData = [
  {
    date: 'Dec 2023 - still active',
    role: 'General Practitioner',
    clinic: 'Aswan Oncology center',
    class: '',
  },
  {
    date: 'Dec 2022 - still active',
    role: 'Dental operator',
    clinic: 'red crescent hospital',
    class: '',
  },
  {
    date: 'Nov 2022 - oct 2023 ',
    role: 'Dental operator',
    clinic: 'Senany dental clinics ',
    class: 'Class A dental clinics',
  },
  {
    date: 'Apr 2022 - Jul 2022',
    role: 'Observer and Assistant',
    clinic: 'Dr Ahmed Abdel Radi, Qena',
    class: 'Class A clinic',
  },
  {
    date: 'Feb 2022 - Nov 2022',
    role: 'Dental operator',
    clinic: 'Dr Doaa Mohamed, Qus-Qena',
    class: 'Class B clinic',
  },
  {
    date: 'Feb 2022 - Nov 2022',
    role: 'Dental operator',
    clinic: 'Dr Masoud Clinic, Qena',
    class: 'Class B Clinic',
  },
  {
    date: 'Jul 2020 - Oct 2020',
    role: 'Observer and Assistant',
    clinic: 'Dr Elfeel Clinic',
    class: 'Class A clinic',
  },
];

export const coursesData = [
  {
    date: 'Sep 2022 - Aug 2025',
    course: 'ORE course',
  },
  {
    date: '25 Aug 2023 - 28 Aug 2023',
    course: 'Practice online endodontic program',
  },
  {
    date: 'Jun 2022 - Jun 2022',
    course: 'Basic and advanced removable prosthodontics',
  },
  {
    date: 'Apr 2022 - Apr 2022',
    course: 'Basic pediatric dentistry program',
  },
  {
    date: 'Feb 2022 - Feb 2022',
    course: 'Anterior and posterior composite restorations',
  },
  {
    date: 'Nov 2021 - Nov 2021',
    course: 'mastering fixed prosthodontics and DSD program',
  },
  {
    date: 'Oct 2021 - Oct 2021',
    course: 'Basic and advanced minor surgery (25 credit hours)',
  },
];

export const skillsData = [
  {
    title: 'C1 proficiency level in English',
  },
  { title: '7.0 overall score band ( academic ILETS)' },
  { title: 'Good clinic and patient management skills' },
  {
    title:
      'Expert in providing dental care for elderly patients and those medically compromised and those receiving cancer treatments like chemotherapy, radiotherapy, and hormonal therapy',
  },
];

export const endoImages = [
  {
    src: '/endo/1.png',
    alt: 'endo1',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/2.png',
    alt: 'endo2',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/3.png',
    alt: 'endo3',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/4.png',
    alt: 'endo4',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/5.png',
    alt: 'endo5',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/6.png',
    alt: 'endo6',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/7.png',
    alt: 'endo7',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/8.png',
    alt: 'endo8',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/9.png',
    alt: 'endo9',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/10.png',
    alt: 'endo10',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/11.png',
    alt: 'endo11',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/12.png',
    alt: 'endo12',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/13.png',
    alt: 'endo13',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/14.png',
    alt: 'endo14',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/15.png',
    alt: 'endo15',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/16.png',
    alt: 'endo16',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/17.png',
    alt: 'endo17',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/18.png',
    alt: 'endo18',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/19.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/20.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/21.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/22.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/23.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/24.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/25.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/26.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/27.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/28.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/29.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/30.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/31.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/32.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/33.png',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/34.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/35.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/36.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/37.JPG',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/38.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/39.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/40.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/41.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/42.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/43.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
  {
    src: '/endo/44.jpg',
    alt: 'endo19',
    caption: '',
    tags: [{ title: 'Endo', value: 'endo' }],
    width: 500,
    height: 500,
  },
];

export const estheticImages = [
  {
    src: '/esthetics/19.JPG',
    alt: 'esthetic1',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/22.JPG',
    alt: 'esthetic2',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/18.JPG',
    alt: 'esthetic3',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/15.PNG',
    alt: 'esthetic4',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/6.png',
    alt: 'esthetic5',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/7.png',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/8.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/9.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/10.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/11.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/12.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/13.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/14.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/5.png',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/16.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/17.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/3.PNG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/1.png',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/20.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/21.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/2.jpg',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/23.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
  {
    src: '/esthetics/24.JPG',
    alt: 'esthetic7',
    caption: '',
    tags: [{ title: 'Esthetics', value: 'esthetic' }],
    width: 500,
    height: 500,
  },
];

export const fixedImages = [
  {
    src: '/fixed/1.png',
    alt: 'fixed1',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/2.png',
    alt: 'fixed2',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/3.png',
    alt: 'fixed3',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/4.png',
    alt: 'fixed4',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/5.png',
    alt: 'fixed5',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/5.png',
    alt: 'fixed5',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/6.JPG',
    alt: 'fixed5',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
  {
    src: '/fixed/7.JPG',
    alt: 'fixed5',
    caption: '',
    tags: [{ title: 'Fixed', value: 'fixed' }],
    width: 500,
    height: 500,
  },
];

export const surgeryImages = [
  {
    src: '/surgery/1.png',
    alt: 'surgery1',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/2.png',
    alt: 'surgery2',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/3.png',
    alt: 'surgery3',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/4.png',
    alt: 'surgery4',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/5.png',
    alt: 'surgery5',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/6.png',
    alt: 'surgery6',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/7.png',
    alt: 'surgery7',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/8.png',
    alt: 'surgery8',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/9.png',
    alt: 'surgery9',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
  {
    src: '/surgery/10.png',
    alt: 'surgery10',
    caption: '',
    tags: [{ title: 'Surgery', value: 'surgery' }],
    width: 500,
    height: 500,
  },
];
